### ISSUE TITLE
CronJobSource, GitHubSource...: all statuses have severity:Error but it's working

### ISSUE THREAD

**Issue by ahmetb** [knative/eventing-sources#190]
## Expected Behavior

I followed https://github.com/knative/docs/tree/88a6f7fea6038c43467a5f4da9c1dadb3b4202d0/eventing/samples/cronjob-source sample with eventing v0.3.0 to try things out.

I look at `kubectl get -o=yaml CronJobSource` output and `kubectl describe` outputs to see if anything failed. I expect not to find any errors.

## Actual Behavior

```
kubectl get -o=yaml CronJobSource
...
  status:
    conditions:
    - lastTransitionTime: "2019-01-28T23:42:37Z"
      severity: Error
      status: "True"
      type: Deployed
    - lastTransitionTime: "2019-01-28T23:42:37Z"
      severity: Error
      status: "True"
      type: Ready
    - lastTransitionTime: "2019-01-28T23:42:37Z"
      severity: Error
      status: "True"
      type: SinkProvided
    - lastTransitionTime: "2019-01-28T23:42:37Z"
      severity: Error
      status: "True"
      type: ValidSchedule
...
```

But it actually works fine (makes a request every 2m).

## Steps to Reproduce the Problem

  1. install eventing v0.3.0
  2. apply CronJobSource example in https://github.com/knative/docs/tree/88a6f7fea6038c43467a5f4da9c1dadb3b4202d0/eventing/samples/cronjob-source
  3. `kubectl get -o=yaml CronJobSource`
  4. observe `status:` field for `severity: Error` items.

## Additional Info

GKE cluster with serving v0.3 and eventing v0.3.
